version: '2'

services:

  cassandra:
    image: cassandra

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "worker_commands:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  clustershardedapp:
    image: clustershardedapp:1.0
    links:
      - "cassandra"
      - "kafka"
    depends_on:
      - cassandra
      - kafka
