version: '2'

services:

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "worker_commands:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  clustershardedapp:
    image: clustershardedapp:1.0
    links:
      - "cassandra"
      - "kafka"
    depends_on:
      - cassandra
      - kafka

# akkahttpkafkaapp service can be use to publish to worker_commands Topic in Kafka by sending Http requests
# akkahttpkafkaapp service can be found here - https://github.com/alanphillips78/akka-http-kafka-streams
# To use here and publish to Kafka using http, do a docker publish locally of akkahttpkafkaapp , uncomment the entry below and launch all using docker-compose
# Then observe that clustershardedapp will consume these messages and persist these to cassandra

#  akkahttpkafkaapp:
#    image: akka-http-kafka-streams:1.0
#    ports:
#      - "8081:8081"
#    links:
#      - "kafka"
#    depends_on:
#      - kafka
#      - clustershardedapp
